export const BASE_URL = '/api';

/**
 * url constants
 * @type {{}}
 */
export const URL_CONSTANTS: any = {
    authorization: `${BASE_URL}/authorization`,
    settingsPerson: `${BASE_URL}/profiles/my/person`,
    news: `${BASE_URL}/conversations`,
    loyaltyRules: `${BASE_URL}/loyalty-rules`,
    pos: `${BASE_URL}/points-of-sale`,
    settings: `${BASE_URL}/profiles/my`,
    loyaltyGroup: `${BASE_URL}/loyalty-groups`,
    merchantPayments: `/${BASE_URL}/merchant-payments`,
    products: `${BASE_URL}/merchant-products`,
    measure: `${BASE_URL}/merchant-measure-units`,
    mediaFiles: `${BASE_URL}/media-files`,
    issuers: `${BASE_URL}/issuers`,
    categories: `${BASE_URL}/merchant-product-categories`,
    resetPass: `${BASE_URL}/password/recovery`,
    clients: `${BASE_URL}/users`,
    smartCards: `${BASE_URL}/smart-cards`,
    createClient: `${BASE_URL}/registration`,
    newsCreate: `${BASE_URL}/conversations/create-system-broadcasts`,
    bonuses: `${BASE_URL}/merchant-payments`,
    newClients: `${BASE_URL}/statistic/smart-cards-count`,
    allUsers: `${BASE_URL}/statistic/individuals-count`,
    bundleConfigurator: `${BASE_URL}/i18n-records`,
    invoices: `${BASE_URL}/invoices`,
    invoiceTemplates: `${BASE_URL}/invoice-templates`,
    bank: `${BASE_URL}/profiles/my/bank-accounts`,
    gate: `${BASE_URL}/gate`,
    coins: `${BASE_URL}/coins`,
    prepaid: `${BASE_URL}/prepaid-coins`,
    transactions: `${BASE_URL}/transactions`,
    transfers: `${BASE_URL}/transfers`,
    bankWithdrawal: `${BASE_URL}/bank-withdrawals`,
    profileDocuments: `${BASE_URL}/profile-documents`,
    profiles: `${BASE_URL}/profiles`,
    organizations: `${BASE_URL}/organizations`,
    conversations: `${BASE_URL}/conversations`,
    exchange: `${BASE_URL}/exchange-rates`,
    currencies: `${BASE_URL}/currencies`,
    contracts: `${BASE_URL}/contracts`,
    gateProviders: `${BASE_URL}/gate-provider-accounts`,
    cardHolds: `${BASE_URL}/invoice-card-holds`,
    investment: `${BASE_URL}/investments`,
    collects: `${BASE_URL}/collects`,
    inputs: `${BASE_URL}/inputs`,
    workingDays: `${BASE_URL}/working-days`,
    cashDesks: `${BASE_URL}/cash-desks`,
    cashDeskTopUp: `${BASE_URL}/cash-desk-top-ups`,
    cashDeskWithdrawal: `${BASE_URL}/cash-desk-withdrawals`,
    registration: `${BASE_URL}/registration`,
    contacts: `${BASE_URL}/contacts`,
    gateInvestment: `${BASE_URL}/gate-investments`
};
